<div class="container">
    <div class="page-header">
        <h1>Empresa</h1>
    </div>
    <img src="img/empresa.jpg" alt="..." class="img-thumbnail" style="float: left; margin-right: 5px;" width="160">
    <p class="lead">"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed commodo quam, ac tempus libero. Nullam mattis dui ac neque pretium, in lobortis nisi varius. Donec aliquam lobortis nisl, sit amet luctus nibh feugiat quis. Aliquam venenatis nec elit nec semper. Duis ipsum velit, varius a elit ac, venenatis bibendum elit. Sed convallis blandit ligula at facilisis. Phasellus et orci tortor. Duis orci est, imperdiet at nunc vitae, consequat porttitor ipsum. Sed eu enim sed dui lobortis fringilla ut sed velit. Nunc pharetra ante et ante blandit semper. Donec dapibus sit amet massa at ullamcorper. Pellentesque sed libero ligula. Donec pellentesque diam gravida odio hendrerit congue.
        <br />
        Maecenas feugiat est sed dolor pellentesque feugiat. Vivamus posuere dapibus nunc sed semper. Proin sollicitudin nisi dui. Nam non magna ullamcorper, malesuada dui eget, vestibulum purus. Nullam vitae commodo justo. Donec sed est ut eros egestas dapibus. Phasellus at rhoncus erat. Curabitur pharetra pellentesque feugiat. Praesent turpis lacus, ornare nec tempor id, tincidunt vitae massa. Donec dictum nulla non elit viverra placerat. Aliquam et neque rhoncus, ultricies eros a, tincidunt ante. Aenean tincidunt dignissim dui vitae tincidunt. Nullam ut vestibulum metus, in viverra est. Ut eget vehicula lectus, pretium egestas lectus.
        <br />
        Duis quis nisl at lorem eleifend volutpat. Duis in commodo mauris. Cras elit odio, laoreet a malesuada eget, lobortis nec erat. Nulla tellus arcu, pharetra eu lectus eget, semper cursus odio. Etiam ac nisl vitae nibh egestas fermentum vel nec elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus eget neque dolor. Sed ac mi varius, imperdiet nunc ac, interdum elit. In ultrices in tellus eget adipiscing. Integer neque elit, molestie sit amet lorem vel, placerat pretium erat. Pellentesque vitae ultricies tellus, a feugiat tortor. Etiam dui leo, vulputate at erat non, cursus ullamcorper lectus. Vestibulum at nibh ullamcorper, accumsan massa vel, faucibus nisl.
        <br />
        Phasellus eros nibh, rhoncus ut faucibus et, gravida quis lacus. Donec vel ultrices lacus. Morbi eget condimentum augue. Nulla metus nibh, ornare ac neque quis, rutrum ornare nulla. Vestibulum id ligula mollis, auctor felis sed, pulvinar neque. Etiam mollis sagittis dui, malesuada viverra neque fermentum vitae. Aenean molestie ante diam, ut egestas dolor euismod nec. Sed eget sapien viverra ligula vulputate interdum. Donec in nisi pharetra, gravida nulla sed, mollis sapien. Quisque eget rutrum lacus. Duis vel mollis urna, nec commodo enim. Proin mollis ipsum at nunc vulputate, a interdum metus sagittis.
        <br />
        Fusce in lorem sed libero sagittis porta ac a diam. In quis nisi ac arcu consequat rhoncus et eu magna. Phasellus ultricies urna ac magna bibendum, consequat congue lacus feugiat. Nunc tristique egestas orci, vitae semper augue pretium et. Maecenas in mauris sed sem iaculis gravida. Sed euismod gravida enim porttitor ullamcorper. Nullam luctus arcu odio, nec aliquet enim fringilla ut.
    </p>
</div>